### ISSUE TITLE
Copernicus DEM archive not complete?

### ISSUE THREAD

**Issue by florianbeyer** [SAR-ARD/S1_NRB#42]
I think I accidentally hit a region in Germany where there is no DEM tile on aws, right?

Is there another source for the tif files?

``` Python
/home/eouser/.snap/auxdata/dem/Copernicus 30m Global DEM/Copernicus_DSM_COG_10_N52_00_E007_00_DEM.tif <<-- https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N52_00_E007_00_DEM/Copernicus_DSM_COG_10_N52_00_E007_00_DEM.tif
/home/eouser/.snap/auxdata/dem/Copernicus 30m Global DEM/Copernicus_DSM_COG_10_N54_00_E012_00_DEM.tif <<-- https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N54_00_E012_00_DEM/Copernicus_DSM_COG_10_N54_00_E012_00_DEM.tif
/home/eouser/.snap/auxdata/dem/Copernicus 30m Global DEM/Copernicus_DSM_COG_10_N54_00_E006_00_DEM.tif <<-- https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N54_00_E006_00_DEM/Copernicus_DSM_COG_10_N54_00_E006_00_DEM.tif
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nrb_env/bin/s1_nrb", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/cli.py", line 18, in cli
    S1_NRB.process(config_file=config_file, section_name=section, debug=debug)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/processor.py", line 93, in main
    dem.prepare(geometries=geometries, threads=gdal_prms['threads'],
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/dem.py", line 99, in prepare
    dem_autoload([geometry], demType=dem_type,
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/auxdata.py", line 224, in dem_autoload
    return handler.load(demType=demType,
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/auxdata.py", line 739, in load
    locals = self.__retrieve(self.config[demType]['url'], remotes, outdir)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/auxdata.py", line 490, in __retrieve
    r.raise_for_status()
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N54_00_E006_00_DEM/Copernicus_DSM_COG_10_N54_00_E006_00_DEM.tif
(nrb_env) eouser@jupyterhub:~/data_storage/florian/S1_NRB$ cd /home/eouser/.snap/auxdata/dem/Copernicus\ 30m\ Global\ DEM
(nrb_env) eouser@jupyterhub:~/.snap/auxdata/dem/Copernicus 30m Global DEM$ wget  https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N54_00_E006_00_DEM/Copernicus_DSM_COG_10_N54_00_E006_00_DEM.tif
--2022-06-24 14:09:55--  https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N54_00_E006_00_DEM/Copernicus_DSM_COG_10_N54_00_E006_00_DEM.tif
Resolving copernicus-dem-30m.s3.eu-central-1.amazonaws.com (copernicus-dem-30m.s3.eu-central-1.amazonaws.com)... 52.219.47.112
Connecting to copernicus-dem-30m.s3.eu-central-1.amazonaws.com (copernicus-dem-30m.s3.eu-central-1.amazonaws.com)|52.219.47.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-24 14:09:55 ERROR 404: Not Found.

```

[Copernicus_DSM_COG_10_N54_00_E006_00_DEM.tif](https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N54_00_E006_00_DEM/Copernicus_DSM_COG_10_N54_00_E006_00_DEM.tif
)

**Comment by johntruckenbrodt** [comment]
Fix is in the making.. https://github.com/johntruckenbrodt/pyroSAR/pull/214.
