### ISSUE TITLE
`ValueError: Invalid integer data type 'f'.` during DEM MGRS creation?

### ISSUE THREAD

**Issue by florianbeyer** [SAR-ARD/S1_NRB#43]
``` Python
/home/eouser/.snap/auxdata/dem/Copernicus 30m Global DEM/Copernicus_DSM_COG_10_N48_00_E011_00_DEM.tif <<-- https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N48_00_E011_00_DEM/Copernicus_DSM_COG_10_N48_00_E011_00_DEM.tif
/home/eouser/.snap/auxdata/dem/Copernicus 30m Global DEM/Copernicus_DSM_COG_10_N47_00_E010_00_DEM.tif <<-- https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N47_00_E010_00_DEM/Copernicus_DSM_COG_10_N47_00_E010_00_DEM.tif
/home/eouser/.snap/auxdata/dem/Copernicus 30m Global DEM/Copernicus_DSM_COG_10_N46_00_E013_00_DEM.tif <<-- https://copernicus-dem-30m.s3.eu-central-1.amazonaws.com/Copernicus_DSM_COG_10_N46_00_E013_00_DEM/Copernicus_DSM_COG_10_N46_00_E013_00_DEM.tif
### creating DEM MGRS tiles:
['32UMA', '32UMU', '32UMV', '32UNA', '32UNU', '32UNV', '32UPA', '32UPU', '32UPV', '32UQA', '32UQU', '32UQV', '33UUP_32632', '33UUQ_32632', '33UUR_32632']
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nrb_env/bin/s1_nrb", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/cli.py", line 18, in cli
    S1_NRB.process(config_file=config_file, section_name=section, debug=debug)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/processor.py", line 93, in main
    dem.prepare(geometries=geometries, threads=gdal_prms['threads'],
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/dem.py", line 111, in prepare
    dem_create(src=fname_dem_tmp, dst=filename,
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/auxdata.py", line 323, in dem_create
    nodata = np.iinfo(Dtype(dtype_tmp).numpystr).max
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/numpy/core/getlimits.py", line 656, in __init__
    raise ValueError("Invalid integer data type %r." % (self.kind,))
ValueError: Invalid integer data type 'f'.
```

I've got the next issue... this time I do not know, what could be the reason...

**Comment by maawoo** [comment]
Hi @florianbeyer,
this is a pyroSAR issue (`pyroSAR.auxdata.dem_create` to be specific). Would you mind posting it in pyroSAR's GitHub repository instead?

**Comment by johntruckenbrodt** [comment]
No need to report it twice. Thanks @florianbeyer for reporting it. We'll take care of it.

**Comment by florianbeyer** [comment]
thanks you very much guys... @johntruckenbrodt  @maawoo

**Comment by johntruckenbrodt** [comment]
Fix is in the making.. https://github.com/johntruckenbrodt/pyroSAR/pull/214.
