### ISSUE TITLE
Process breaks during GEOCODE process

### ISSUE THREAD

**Issue by florianbeyer** [SAR-ARD/S1_NRB#44]
Hello again ;-)

I fixed my DEM issues.
However, I'm facing a new problem during GEOCODE process, although I updated the S1TBX:

Here is the log file:

``` Python
    ====================================================================================================================
    PROCESSING CONFIGURATION

    mode = all
    aoi_tiles = ['32UNA']
    aoi_geometry = None
    mindate = 2020-05-31T00:00:00
    maxdate = 2020-06-02T00:00:00
    acq_mode = IW

    work_dir = /media/data_storage/data_storage/florian/S1_NRB/work
    scene_dir = /codede/Sentinel-1/SAR/SLC/2020/06/01
    rtc_dir = /media/data_storage/data_storage/florian/S1_NRB/work/RTC
    tmp_dir = /media/data_storage/data_storage/florian/S1_NRB/work/TMP
    nrb_dir = /media/data_storage/data_storage/florian/S1_NRB/work/NRB
    dem_dir = /media/data_storage/data_storage/florian/S1_NRB/work/DEM
    wbm_dir = /media/data_storage/data_storage/florian/S1_NRB/work/WBM
    log_dir = /media/data_storage/data_storage/florian/S1_NRB/work/LOG
    db_file = /media/data_storage/data_storage/florian/S1_NRB/scenes.db
    kml_file = /media/data_storage/data_storage/florian/S1_NRB/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml
    dem_type = Copernicus 30m Global DEM II

    ====================================================================================================================
    SOFTWARE

    S1_NRB: 1.0.0
    snap-core: 8.0.9 | 202112101916
    snap-s1tbx: 8.0.6 | 202202100514
    python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
    python-pyroSAR: 0.17.2
    python-spatialist: 0.11.0
    python-GDAL: 3.5.0
    gdal_threads = 4

    ====================================================================================================================

[2022-06-30 06:32:28,212] [   ERROR] [GEOCODE] -- /codede/Sentinel-1/SAR/SLC/2020/06/01/S1B_IW_SLC__1SDV_20200601T170709_20200601T170737_021843_029753_7199.SAFE [32632] -- The Terrain-Flattening node does not accept parameter 'outputSigma0'. Please update S1TBX.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/snap/util.py", line 467, in geocode
    tf.parameters['outputSigma0'] = True
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/snap/auxil.py", line 1292, in __setitem__
    raise KeyError('key {} does not exist'.format(key))
KeyError: 'key outputSigma0 does not exist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/processor.py", line 155, in main
    geocode(infile=scene, outdir=out_dir_scene_epsg, t_srs=epsg, tmpdir=tmp_dir_scene_epsg,
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/snap/util.py", line 469, in geocode
    raise RuntimeError("The Terrain-Flattening node does not accept "
RuntimeError: The Terrain-Flattening node does not accept parameter 'outputSigma0'. Please update S1TBX.
[2022-06-30 06:32:28,314] [   ERROR] [GEOCODE] -- /codede/Sentinel-1/SAR/SLC/2020/06/01/S1B_IW_SLC__1SDV_20200601T170735_20200601T170801_021843_029753_DFD0.SAFE [32632] -- The Terrain-Flattening node does not accept parameter 'outputSigma0'. Please update S1TBX.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/snap/util.py", line 467, in geocode
    tf.parameters['outputSigma0'] = True
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/snap/auxil.py", line 1292, in __setitem__
    raise KeyError('key {} does not exist'.format(key))
KeyError: 'key outputSigma0 does not exist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/processor.py", line 155, in main
    geocode(infile=scene, outdir=out_dir_scene_epsg, t_srs=epsg, tmpdir=tmp_dir_scene_epsg,
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/snap/util.py", line 469, in geocode
    raise RuntimeError("The Terrain-Flattening node does not accept "
RuntimeError: The Terrain-Flattening node does not accept parameter 'outputSigma0'. Please update S1TBX.
[2022-06-30 06:32:30,709] [   ERROR] [    NRB] -- ['/codede/Sentinel-1/SAR/SLC/2020/06/01/S1B_IW_SLC__1SDV_20200601T170709_20200601T170737_021843_029753_7199.SAFE', '/codede/Sentinel-1/SAR/SLC/2020/06/01/S1B_IW_SLC__1SDV_20200601T170735_20200601T170801_021843_029753_DFD0.SAFE'] [32632] -- list index out of range
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/processor.py", line 219, in main
    msg = nrb.format(config=config, scenes=scenes, datadir=config['rtc_dir'], outdir=outdir,
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/nrb.py", line 85, in format
    src_ids, snap_datasets, snap_datamasks = get_datasets(scenes=scenes, datadir=datadir,
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/nrb.py", line 329, in get_datasets
    snap_dm_ras = re.sub(pattern, 'datamask', pols[0])
IndexError: list index out of range

```

**Comment by florianbeyer** [comment]
`The Terrain-Flattening node does not accept parameter 'outputSigma0'

I thought Beta0 is the input for Terrain Flattening?

**Comment by maawoo** [comment]
Hi @florianbeyer,
could you check the following: 

```python
from pyroSAR.snap.auxil import parse_node
tf = parse_node('Terrain-Flattening')
tf.parameters
```

The output of `tf.parameters` is a dictionary and in my case it also includes the key value pair `'outputSigma0': 'false'`. I guess this is not the case for you?

**Comment by johntruckenbrodt** [comment]
This is weird. The parameter `outputSigma0` was introduced fairly recently with S1TBX 8.0.5 or 8.0.6. Since you are using 8.0.6 this should work. If Marco's check does not return this parameter, try deleting the file `~/.pyrosar/snap/nodes/8.0.6/Terrain-Flattening.xml` and running it again.

**Comment by florianbeyer** [comment]
``` python
tf.parameters
{
'sourceBands': None, 
'demName': 'SRTM 1Sec HGT',
 'demResamplingMethod': 'BILINEAR_INTERPOLATION',
 'externalDEMFile': None,
 'externalDEMNoDataValue': '0',
 'externalDEMApplyEGM': 'false',
 'outputSimulatedImage': 'false',
 'additionalOverlap': '0.1',
 'oversamplingMultiple': '1.0'}

```

**Comment by florianbeyer** [comment]
Nope... unfortunately not. I deleted the XML, restarted the process and same error happend.
And the dict is also the same as before.

**Comment by florianbeyer** [comment]
```
(nrb_env) ***@****:~$ /opt/snap/bin/gpt Terrain-Flattening -h
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.s2tbx.dataio.gdal.GDALVersion: Incompatible GDAL 3.5.0 found on system. Internal GDAL 3.0.0 from distribution will be used.
INFO: org.esa.s2tbx.dataio.gdal.GDALVersion: Internal GDAL 3.0.0 set to be used by SNAP.
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.esa.s2tbx.dataio.gdal.GDALVersion: Internal GDAL 3.0.0 set to be used by SNAP.
Usage:
  gpt Terrain-Flattening [options]

Description:
  Terrain Flattening


Source Options:
  -Ssource=<file>    Sets source 'source' to <filepath>.
                     This is a mandatory source.

Parameter Options:
  -PadditionalOverlap=<double>                The additional overlap percentage
                                              Valid interval is [0, 1].
                                              Default value is '0.1'.
  -PdemName=<string>                          The digital elevation model.
                                              Default value is 'SRTM 1Sec HGT'.
  -PdemResamplingMethod=<string>              Sets parameter 'demResamplingMethod' to <string>.
                                              Default value is 'BILINEAR_INTERPOLATION'.
  -PexternalDEMApplyEGM=<boolean>             Sets parameter 'externalDEMApplyEGM' to <boolean>.
                                              Default value is 'false'.
  -PexternalDEMFile=<file>                    Sets parameter 'externalDEMFile' to <file>.
  -PexternalDEMNoDataValue=<double>           Sets parameter 'externalDEMNoDataValue' to <double>.
                                              Default value is '0'.
  -PoutputSimulatedImage=<boolean>            Sets parameter 'outputSimulatedImage' to <boolean>.
                                              Default value is 'false'.
  -PoversamplingMultiple=<double>             The oversampling factor
                                              Valid interval is [1, 4].
                                              Default value is '1.0'.
  -PsourceBands=<string,string,string,...>    The list of source bands.

Graph XML Format:
  <graph id="someGraphId">
    <version>1.0</version>
    <node id="someNodeId">
      <operator>Terrain-Flattening</operator>
      <sources>
        <source>${source}</source>
      </sources>
      <parameters>
        <sourceBands>string,string,string,...</sourceBands>
        <demName>string</demName>
        <demResamplingMethod>string</demResamplingMethod>
        <externalDEMFile>file</externalDEMFile>
        <externalDEMNoDataValue>double</externalDEMNoDataValue>
        <externalDEMApplyEGM>boolean</externalDEMApplyEGM>
        <outputSimulatedImage>boolean</outputSimulatedImage>
        <additionalOverlap>double</additionalOverlap>
        <oversamplingMultiple>double</oversamplingMultiple>
      </parameters>
    </node>
  </graph>

```

**Comment by johntruckenbrodt** [comment]
Okay, so there we can't see that parameter either. You can run the following to get info on the paths to the `snap` and `gpt` executables:
```python
from pyroSAR.examine import ExamineSnap
info = ExamineSnap()
print(info.path)
print(info.gpt)
```
Are they pointing to the same directory? It is really strange that SNAP reports one version of the software but the GPT command obviously is in a different one. Perhaps you can try to run another update.

Oh and by the way, this parameter is not an input to the command but an additional output. It enables writing of sigma nought RTC as addition to gamma nought RTC.

**Comment by florianbeyer** [comment]
@johntruckenbrodt thank you for your ongoing support...

both are pointing to the same dir:

````
/opt/snap/bin/snap
/opt/snap/bin/gpt
```

**Comment by johntruckenbrodt** [comment]
Another thing you can try is to start the GUI (if you can on your machine) and check whether the parameter is present in the graph builder.

**Comment by florianbeyer** [comment]
no its a remote machine without desktop

**Comment by maawoo** [comment]
Are you connecting via SSH? Try `ssh -X <user>@<host>` (or alternatively with the`-Y` flag) and then type `snap` in the terminal. That should open the SNAP GUI, which is forwarded from the remote machine. If your local OS is Windows and you're using MobaXTerm, you don't have to do anything to enables this. 

How are you handling updates of SNAP? Via command line as described [here](https://senbox.atlassian.net/wiki/spaces/SNAP/pages/30539785/Update+SNAP+from+the+command+line)?

**Comment by florianbeyer** [comment]
I'm using MobaXterm and connect to an Ubuntu machine on CODE-DE. I did not installed a Desktop. I used `/opt/snap/bin/snap --nosplash --nogui --modules --update-all` for updating on command line.

**Comment by johntruckenbrodt** [comment]
@maawoo X11 is not necessarily supported.

**Comment by florianbeyer** [comment]
1. I updated again as @maawoo recommended, but I get the same error.

2. I installed snap and S1_NRB from scratch on 2 other machines (on one machine with snap 9 and the other machine snap 8 as recommended in your documentation)  -> I unfortunaltely get a new issue: https://github.com/SAR-ARD/S1_NRB/issues/46

**Comment by florianbeyer** [comment]
@maawoo same error

**Comment by maawoo** [comment]
> @maawoo same error

Are you 100% sure that the `config.ini` you have used included the DEM option `Copernicus 30m Global DEM` (without the `II` suffix)? It should not trigger anything that is related to the water body mask.

**Comment by florianbeyer** [comment]
```
(nrb_env) eouser@gpumachine:~/data_storage/florian/S1_NRB$ cat config.ini
````

```
########################################################################################################################

# This is an example configuration file for the S1_NRB prototype processor. Please refer to the documentation for
# further details about individual parameters and usage in general:

# https://s1-nrb.readthedocs.io/en/latest/general/usage.html#usage

########################################################################################################################

[PROCESSING]

# OPTIONS: all | nrb | snap
mode = all

# Only one of the following parameters is required!
# [aoi_tiles] expects a comma-separated list of MGRS tile IDs
# [aoi_geometry] expects a full path to a vector file (GeoJSON, GPKG, KML or Shapefile)
aoi_tiles = 32UPC
aoi_geometry = None

# Allowed date formats: %Y-%m-%d | %Y-%m-%dT%H:%M:%S
mindate = 2020-05-31
maxdate = 2020-06-02

# OPTIONS: IW | EW | SM
acq_mode = IW

# OPTIONS: GRD | SLC
product = SLC

# Must be full paths to existing directories.
work_dir = /media/data_storage/florian/S1_NRB/work
# scene_dir = /media/data_storage/data_storage/florian/S1_NRB/scences
scene_dir = /codede/Sentinel-1/SAR/SLC/2020/06/01

# Recommended to use the following default values, which automatically creates subdirectories of [work_dir]
# (e.g., `/<work_dir>/NRB`). Alternatively, full paths to existing directories can be provided.
rtc_dir = RTC
tmp_dir = TMP
nrb_dir = NRB
dem_dir = DEM
wbm_dir = WBM
log_dir = LOG

# Files are expected to be located in [work_dir] (e.g., `/<work_dir>/scene.db`). However, full paths can also be provided.
# [db_file] The database to index scenes found in [scene_dir] will be generated by pyroSAR if it doesn't exist already.
# [kml_file] The Sentinel-2 Military Grid Reference System (MGRS) tiling system can be retrieved as a KML file from:
# https://sentinel.esa.int/documents/247904/1955685/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml
db_file = /media/data_storage/florian/S1_NRB/scenes.db
kml_file = /media/data_storage/florian/S1_NRB/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml

# OPTIONS: Copernicus 10m EEA DEM | Copernicus 30m Global DEM II | Copernicus 30m Global DEM | GETASSE30
# The names are taken from the options of function https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.auxdata.dem_autoload.
# 'Copernicus 30m Global DEM' and 'GETASSE30' do not include a water body mask.
# Copernicus 10m EEA DEM and Copernicus 30m Global DEM II include a water body mask. Retrieval requires registration via:
# https://spacedata.copernicus.eu/web/cscda/data-access/registration
# Authentication credentials can be set via environment variables 'DEM_USER' and 'DEM_PASS' or interactively during processor runs.
#dem_type = Copernicus 30m Global DEM
dem_type = Copernicus 30m Global DEM

# Temporarily changes GDAL_NUM_THREADS during processing. Will be reset after processing has finished.
gdal_threads = 4

# Should ETAD correction be performed on SLCs? If [etad] is False, [etad_dir] will be ignored,
# otherwise [etad_dir] is searched recursively for ETAD products matching the defined SLCs.
etad = False
etad_dir = /example/etad/directory

[METADATA]
# The metadata files created for each S1-NRB product contain some fields that should not be hidden away and hardcoded
# with arbitrary values. Instead, they can be accessed here in order to more easily generate a complete set of metadata.
# These fields are mostly relevant if you want to produce S1-NRB products systematically and make them available for
# others. If you don't see a need for them you can just leave the fields empty, use the default 'None' or delete this
# entire section.

access_url = None
licence = None
doi = None
processing_center = None

```

**Comment by maawoo** [comment]
Based on your response in #47 your GEOCODE process is not breaking anymore. And regarding the `Copernicus 30m Global DEM` and water body mask, I'm pretty sure we have just ended up talking past each other 😅 If not, feel free to open a separate issue.
