### ISSUE TITLE
 nodata value could not be read from the source file while `creating WBM MGRS tiles`

### ISSUE THREAD

**Issue by florianbeyer** [SAR-ARD/S1_NRB#46]
I have to remote machines (Ubuntu) one with snap 8 and one with snap 9.
Input files are *.SAFE directories for one day over Germany.
I want to process one Tile (32UNA or 32UPC).

I get the same error on every machine while ` creating WBM MGRS tiles` 
``` Python
### creating WBM MGRS tiles:
['32UMA', '32UMB', '32UMC', '32UNA', '32UNB', '32UNC', '32UPA', '32UPB', '32UPC', '32UQA', '32UQB', '32UQC', '33UUS_32632', '33UUT_32632']
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nrb_env/bin/s1_nrb", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/cli.py", line 18, in cli
    S1_NRB.process(config_file=config_file, section_name=section, debug=debug)
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/processor.py", line 93, in main
    dem.prepare(geometries=geometries, threads=gdal_prms['threads'],
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/dem.py", line 124, in prepare
    dem_create(src=fname_wbm_tmp, dst=filename,
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/pyroSAR/auxdata.py", line 300, in dem_create
    raise RuntimeError('the nodata value could not be read from the source file. Please explicitly define it.')
RuntimeError: the nodata value could not be read from the source file. Please explicitly define it.
```

LOG-File SNAP8 machine:
```
===================================================================================================================
    PROCESSING CONFIGURATION

    mode = all
    aoi_tiles = ['32UPC']
    aoi_geometry = None
    mindate = 2020-05-31T00:00:00
    maxdate = 2020-06-02T00:00:00
    acq_mode = IW

    work_dir = /media/data_storage/florian/S1_NRB/work
    scene_dir = /codede/Sentinel-1/SAR/SLC/2020/06/01
    rtc_dir = /media/data_storage/florian/S1_NRB/work/RTC
    tmp_dir = /media/data_storage/florian/S1_NRB/work/TMP
    nrb_dir = /media/data_storage/florian/S1_NRB/work/NRB
    dem_dir = /media/data_storage/florian/S1_NRB/work/DEM
    wbm_dir = /media/data_storage/florian/S1_NRB/work/WBM
    log_dir = /media/data_storage/florian/S1_NRB/work/LOG
    db_file = /media/data_storage/florian/S1_NRB/scenes.db
    kml_file = /media/data_storage/florian/S1_NRB/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml
    dem_type = Copernicus 30m Global DEM II

    ====================================================================================================================
    SOFTWARE

    S1_NRB: 1.0.0
    snap-core: unknown
    snap-s1tbx: unknown
    python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
    python-pyroSAR: 0.17.3
    python-spatialist: 0.11.0
    python-GDAL: 3.5.1
    gdal_threads = 10

    ====================================================================================================================
```

LOG-File SNAP9 machine:
```
    ====================================================================================================================
    PROCESSING CONFIGURATION

    mode = all
    aoi_tiles = ['32UNA']
    aoi_geometry = None
    mindate = 2020-05-31T00:00:00
    maxdate = 2020-06-02T00:00:00
    acq_mode = IW

    work_dir = /media/data_storage/florian/S1_NRB/work
    scene_dir = /codede/Sentinel-1/SAR/SLC/2020/06/01
    rtc_dir = /media/data_storage/florian/S1_NRB/work/RTC
    tmp_dir = /media/data_storage/florian/S1_NRB/work/TMP
    nrb_dir = /media/data_storage/florian/S1_NRB/work/NRB
    dem_dir = /media/data_storage/florian/S1_NRB/work/DEM
    wbm_dir = /media/data_storage/florian/S1_NRB/work/WBM
    log_dir = /media/data_storage/florian/S1_NRB/work/LOG
    db_file = /media/data_storage/florian/S1_NRB/scenes.db
    kml_file = /media/data_storage/florian/S1_NRB/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml
    dem_type = Copernicus 30m Global DEM II

    ====================================================================================================================
    SOFTWARE

    S1_NRB: 1.0.0
    snap-core: 9.0.0 | 202206281505
    snap-s1tbx: 9.0.0 | 202206281601
    python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
    python-pyroSAR: 0.17.3
    python-spatialist: 0.11.0
    python-GDAL: 3.5.1
    gdal_threads = 20

    ====================================================================================================================
```

**Comment by johntruckenbrodt** [comment]
Please update to S1_NRB 1.0.1.
