### ISSUE TITLE
Error reading temporary VRT file

### ISSUE THREAD

**Issue by maawoo** [SAR-ARD/S1_NRB#49]
As reported in #47:

```bash
[S1B_IW_SLC__1SDV_20200601T170735_20200601T170801_021843_029753_DFD0_tmp2.xml] failed with return code 1
[2022-07-07 15:24:08,619] [   ERROR] [    NRB] -- ['/codede/Sentinel-1/SAR/SLC/2020/06/01/S1B_IW_SLC__1SDV_20200601T170709_20200601T170737_021843_029753_7199.SAFE', '/codede/Sentinel-1/SAR/SLC/2020/06/01/S1B_IW_SLC__1SDV_20200601T170735_20200601T170801_021843_029753_DFD0.SAFE'] [32632] -- Error reading file '/tmp/spatialist/tmp4_j3cs_v.vrt': failed to load external entity "/tmp/spatialist/tmp4_j3cs_v.vrt"
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/processor.py", line 219, in main
    msg = nrb.format(config=config, scenes=scenes, datadir=config['rtc_dir'], outdir=outdir,
  File "/opt/anaconda3/envs/nrb_env/lib/python3.10/site-packages/S1_NRB/nrb.py", line 175, in format
    tree = etree.parse(source)
  File "src/lxml/etree.pyx", line 3538, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1902, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file '/tmp/spatialist/tmp4_j3cs_v.vrt': failed to load external entity "/tmp/spatialist/tmp4_j3cs_v.vrt"
```

Relevant lines of code:
https://github.com/SAR-ARD/S1_NRB/blob/d58048efe08d3a64a3bdfcb19c15472d2bb4c8f5/S1_NRB/nrb.py#L160-L175

**Comment by johntruckenbrodt** [comment]
Mh I don't know why this error has not occurred before. This is expected behavior. Once the spatialist `Raster` object is closed, the temporary file is deleted so everything using the file needs needs to happen in the `with Raster...` context. See here:
https://github.com/johntruckenbrodt/spatialist/blob/c4c4277eb191fb41ccf79bb17b2ba2e442f0f1ab/spatialist/raster.py#L612

**Comment by johntruckenbrodt** [comment]
@maawoo was this fixed with https://github.com/SAR-ARD/S1_NRB/pull/50 or is there more to it?

**Comment by maawoo** [comment]
I'm assuming the problem is fixed, so I'll close this now. This issue can be reopened if someone else runs into the same problem again.
